unstable_features = true

condense_wildcard_suffixes = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
reorder_impl_items = true
spaces_around_ranges = true
use_field_init_shorthand = true
use_try_shorthand = true
